# ezstats docker-compose.yml

services:

  ezstats-ezpaarse:
    container_name: ezstats-ezpaarse
    image: ezpaarseproject/ezpaarse:3.9.3
    environment:
      #  http_proxy:  ${http_proxy}
      #  https_proxy: ${https_proxy}
      #  no_proxy: ${no_proxy}
      NODE_ENV: "production"
      EZPAARSE_MONGO_URL: "mongodb://ezstats-ezpaarse-db:27017/ezpaarse"
    volumes:
      - ./ezpaarse/platforms:/opt/ezpaarse/platforms
      - ./ezpaarse/middlewares:/opt/ezpaarse/middlewares
      - ./ezpaarse/resources:/opt/ezpaarse/resources
      - ./ezpaarse/exclusions:/opt/ezpaarse/exclusions
      - ./ezpaarse/config.local.json:/opt/ezpaarse/config.local.json
      - ./ezpaarse/dev:/tmp
      - ./ezpaarse/dev/Makefile:/opt/ezpaarse/Makefile
    mem_limit: ${EZSTATS_MEM_LIMIT}
    memswap_limit: ${EZSTATS_MEMSWAP_LIMIT}
    cpus: ${EZSTATS_CPU_LIMIT}
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the container
    ports:
      - 29599:59599
    depends_on:
      - ezstats-ezpaarse-db
    restart: unless-stopped

  ezstats-ezpaarse-db:
    container_name: ezstats-ezpaarse-db
    image: mongo:3.6.23
    mem_limit: ${EZSTATS_MEM_LIMIT}
    memswap_limit: ${EZSTATS_MEMSWAP_LIMIT}
    cpus: ${EZSTATS_CPU_LIMIT}
    ports:
      - 27017:27017
    restart: unless-stopped

  ezstats-webdav:
    image: bytemark/webdav
    restart: always
    mem_limit: ${EZSTATS_MEM_LIMIT}
    memswap_limit: ${EZSTATS_MEMSWAP_LIMIT}
    cpus: ${EZSTATS_CPU_LIMIT}
    ports:
      - "28080:80"
    environment:
      AUTH_TYPE: Digest
    volumes:
      - ezstats-logs:/var/lib/dav
      - ./webdav/entrypoint.sh:/usr/local/apache2/webdav/entrypoint.sh
      - ./webdav/dav.conf:/usr/local/apache2/webdav/dav.conf
      - ./webdav/user.passwd:/user.passwd
      #command : /bin/sh -c "/usr/local/apache2/webdav/entrypoint.sh"

  ezstats-watchtower:
    image: containrrr/watchtower:1.4.0
    container_name: ezstats-watchtower
    restart: unless-stopped
    networks:
      - default
    mem_limit: ${EZSTATS_MEM_LIMIT}
    memswap_limit: ${EZSTATS_MEMSWAP_LIMIT}
    cpus: ${EZSTATS_CPU_LIMIT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_DEBUG: "false"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_WARN_ON_HEAD_FAILURE: "never"
      WATCHTOWER_RUN_ONCE: ${EZSTATS_WATCHTOWER_RUN_ONCE}
      #WATCHTOWER_NOTIFICATIONS: "slack"
      #WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${EZSTATS_WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}
      #WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: ${EZSTATS_WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER}
      #WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "#notif-ezstats"
      WATCHTOWER_SCOPE: "ezstats-watchtower-scope"
    labels:
      - "com.centurylinklabs.watchtower.scope=ezstats-watchtower-scope"

volumes:
  ezstats-logs:
    driver: local
    driver_opts:
      type: ${EZSTATS_VOLUME_TYPE}
      o: ${EZSTATS_VOLUME_O}
      device: ${EZSTATS_VOLUME_DEVICE}